# Generated by Django 4.2.16 on 2025-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=20)),
                ('year', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('sets_played', models.PositiveIntegerField(default=0)),
                ('serves', models.PositiveIntegerField(default=0)),
                ('serve_aces', models.PositiveIntegerField(default=0)),
                ('serve_errors', models.PositiveIntegerField(default=0)),
                ('digs', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('attacks', models.PositiveIntegerField(default=0)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('attack_errors', models.PositiveIntegerField(default=0)),
                ('receive_errors', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
