# Generated by Django 4.2.16 on 2025-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
