# Generated by Django 4.2.16 on 2025-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
