# Generated by Django 4.2.16 on 2025-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('supporter', 'Supporter'), ('player', 'Player')], default='supporter', max_length=20),
        ),
    ]
