# Generated by Django 4.2.16 on 2025-11-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('Varsity', 'Varsity'), ('JV', 'JV')], default='Varsity', max_length=10),
        ),
    ]
